/*
 * Copyright (C) 2018 Juan J. Martínez
 * 
 * All rights reserved. This complete software or any portion thereof
 * can be used as reference but may not be reproduced in any manner 
 * whatsoever without the express written permission of the owner.
 * 
 * The purpose of this is to be consulted and used as a referece of 
 * functionallyty.
 * 
 * Developed in Mexico City
 * First version, 2018
 *
 */

/**
 *
 * @author Juan J. Martínez
 * @email juanjmtzs@gmail.com
 * @phone +52-1-55-1247-8044
 * @linkedin https://www.linkedin.com/in/juanjmtzs/
 *
 */

package ITCH;

import Handler.ITCHSoupBinTCPNoBytes;
import Handler.ITCHSoupBinTCPYesBytes;
import Handler.MulticastNoBytes;
import Handler.MulticastYesBytes;
import Properties.AppProperties;
import Requester.RequesterNoBytes;
import Requester.RequesterYesBytes;
import Sphere.Main;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

public class ITCHMain extends javax.swing.JFrame {

    public static JFrame windows;
    private boolean outputToFiles = false;
    public static String userHomeFolder = "";

    public static void setUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Main
     */
    /**
     *
     * @author Juan Jesús Martínez Serrano / juanjmtzs@gmail.com
     *
     *
     */
    public ITCHMain() {

        initComponents();

        windows = this;
        ClassLoader classLoader = getClass().getClassLoader();
        ImageIcon img = new ImageIcon(classLoader.getResource("imgs/icon2.png"));

        windows.setIconImage(img.getImage());
        logs.setVisible(false);

        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();
            NimbusLookAndFeel localNimbusLookAndFeel = (NimbusLookAndFeel) UIManager.getLookAndFeel();
            Color derivedColor = localNimbusLookAndFeel.getDerivedColor("nimbusBase", 0.03054375F, -0.3835404F, -0.0980392F, 0, true);
            defaults.put("nimbusOrange", derivedColor);

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {

        }

        containerFields.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Update = new javax.swing.JTextArea();
        DissconnectDo = new javax.swing.JButton();
        connect = new javax.swing.JButton();
        serviceSelector = new javax.swing.JComboBox<>();
        progress = new javax.swing.JProgressBar();
        containerFields = new javax.swing.JPanel();
        toFile = new javax.swing.JCheckBox();
        logs = new javax.swing.JLabel();
        servicename = new javax.swing.JTextField();
        seqnumFin = new javax.swing.JTextField();
        seqnum = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        hostname = new javax.swing.JTextField();
        session = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        sessionLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        seqLabel = new javax.swing.JLabel();
        seqLabelFin = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        printBytes = new javax.swing.JCheckBox();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ipReceiverLabel = new javax.swing.JLabel();
        receiverHost = new javax.swing.JTextField();
        viewMessages = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        logsArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sphere ITCH");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(1100, 800));

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));

        Update.setEditable(false);
        Update.setBackground(new java.awt.Color(242, 242, 242));
        Update.setColumns(20);
        Update.setForeground(new java.awt.Color(38, 38, 38));
        Update.setRows(5);
        Update.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(Update);

        DissconnectDo.setForeground(new java.awt.Color(38, 38, 38));
        DissconnectDo.setText("Dissconnect");
        DissconnectDo.setEnabled(false);
        DissconnectDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DissconnectDoActionPerformed(evt);
            }
        });

        connect.setForeground(new java.awt.Color(38, 38, 38));
        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        serviceSelector.setForeground(new java.awt.Color(38, 38, 38));
        serviceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "NEWS", "LTP", "BBO", "GLIMPSE", "TV", "TV Multicast", "Retransmissions" }));
        serviceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSelectorActionPerformed(evt);
            }
        });

        progress.setBackground(new java.awt.Color(255, 255, 255));
        progress.setOpaque(true);

        containerFields.setBackground(new java.awt.Color(238, 238, 238));

        toFile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        toFile.setText("Logs in Files");
        toFile.setToolTipText("");
        toFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFileActionPerformed(evt);
            }
        });

        logs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logs.setForeground(new java.awt.Color(51, 51, 51));
        logs.setText("Logs:");

        servicename.setBackground(new java.awt.Color(242, 242, 242));
        servicename.setForeground(new java.awt.Color(38, 38, 38));
        servicename.setText("NEWS");
        servicename.setEnabled(false);
        servicename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicenameActionPerformed(evt);
            }
        });

        seqnumFin.setBackground(new java.awt.Color(242, 242, 242));
        seqnumFin.setForeground(new java.awt.Color(38, 38, 38));
        seqnumFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seqnumFinKeyTyped(evt);
            }
        });

        seqnum.setBackground(new java.awt.Color(242, 242, 242));
        seqnum.setForeground(new java.awt.Color(38, 38, 38));
        seqnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seqnumKeyTyped(evt);
            }
        });

        port.setBackground(new java.awt.Color(242, 242, 242));
        port.setForeground(new java.awt.Color(38, 38, 38));
        port.setToolTipText("33333");
        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });
        port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                portKeyTyped(evt);
            }
        });

        hostname.setBackground(new java.awt.Color(242, 242, 242));
        hostname.setForeground(new java.awt.Color(38, 38, 38));
        hostname.setToolTipText("200.200.200.200");
        hostname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hostnameKeyTyped(evt);
            }
        });

        session.setBackground(new java.awt.Color(242, 242, 242));
        session.setForeground(new java.awt.Color(38, 38, 38));
        session.setText(" ");
        session.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sessionKeyTyped(evt);
            }
        });

        password.setBackground(new java.awt.Color(242, 242, 242));
        password.setForeground(new java.awt.Color(38, 38, 38));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        username.setBackground(new java.awt.Color(242, 242, 242));
        username.setForeground(new java.awt.Color(38, 38, 38));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel.setText("Username*:");

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordLabel.setText("Password*:");

        sessionLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sessionLabel.setForeground(new java.awt.Color(51, 51, 51));
        sessionLabel.setText("Session*:");

        ipLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(51, 51, 51));
        ipLabel.setText("IP*:");

        portLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        portLabel.setForeground(new java.awt.Color(51, 51, 51));
        portLabel.setText("Port*:");

        seqLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seqLabel.setForeground(new java.awt.Color(51, 51, 51));
        seqLabel.setText("Sequence Number*:");

        seqLabelFin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seqLabelFin.setForeground(new java.awt.Color(51, 51, 51));
        seqLabelFin.setText("Final Sequence*: ");

        serviceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        serviceLabel.setForeground(new java.awt.Color(51, 51, 51));
        serviceLabel.setText("Service Name:");

        printBytes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printBytes.setText("Print Bytes");
        printBytes.setToolTipText("");
        printBytes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBytesActionPerformed(evt);
            }
        });

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/save.png"))); // NOI18N
        save.setToolTipText("Save Service Configuration");
        save.setPreferredSize(new java.awt.Dimension(31, 31));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clear.png"))); // NOI18N
        clear.setPreferredSize(new java.awt.Dimension(31, 31));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        ipReceiverLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ipReceiverLabel.setForeground(new java.awt.Color(51, 51, 51));
        ipReceiverLabel.setText("Receiver IP:");

        receiverHost.setBackground(new java.awt.Color(242, 242, 242));
        receiverHost.setForeground(new java.awt.Color(38, 38, 38));
        receiverHost.setToolTipText("200.200.200.200");
        receiverHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receiverHostKeyTyped(evt);
            }
        });

        viewMessages.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewMessages.setSelected(true);
        viewMessages.setText("View Messages");
        viewMessages.setToolTipText("");
        viewMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMessagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerFieldsLayout = new javax.swing.GroupLayout(containerFields);
        containerFields.setLayout(containerFieldsLayout);
        containerFieldsLayout.setHorizontalGroup(
            containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(containerFieldsLayout.createSequentialGroup()
                        .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerFieldsLayout.createSequentialGroup()
                                .addComponent(toFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(printBytes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerFieldsLayout.createSequentialGroup()
                        .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(sessionLabel)
                            .addComponent(ipLabel)
                            .addComponent(portLabel)
                            .addComponent(seqLabel)
                            .addComponent(serviceLabel)
                            .addComponent(seqLabelFin)
                            .addComponent(ipReceiverLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(receiverHost)
                            .addComponent(hostname)
                            .addComponent(session, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(username)
                            .addComponent(password)
                            .addComponent(servicename)
                            .addComponent(seqnumFin)
                            .addComponent(seqnum)
                            .addComponent(port)))))
        );
        containerFieldsLayout.setVerticalGroup(
            containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionLabel)
                    .addComponent(session, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipLabel)
                    .addComponent(hostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipReceiverLabel)
                    .addComponent(receiverHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seqLabel)
                    .addComponent(seqnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seqLabelFin)
                    .addComponent(seqnumFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceLabel)
                    .addComponent(servicename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(containerFieldsLayout.createSequentialGroup()
                        .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toFile)
                            .addComponent(viewMessages))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printBytes)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        logsArea.setBackground(new java.awt.Color(242, 242, 242));
        logsArea.setColumns(20);
        logsArea.setForeground(new java.awt.Color(38, 38, 38));
        logsArea.setRows(5);
        jScrollPane2.setViewportView(logsArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(containerFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 189, Short.MAX_VALUE)
                        .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DissconnectDo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(serviceSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DissconnectDo)
                    .addComponent(connect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("ITCH Feeds", jPanel2);

        jMenu1.setText("About");

        jMenuItem1.setText("Copyright ©");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("by Juan J. Martínez");
        jMenu2.setEnabled(false);
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DissconnectDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DissconnectDoActionPerformed
        // TODO add your handling code here:

        switch (serviceSelector.getSelectedIndex()) {

            case 6:
                progress.setIndeterminate(false);
                connect.setEnabled(true);
                serviceSelector.setEnabled(true);
                DissconnectDo.setEnabled(false);
                printBytes.setEnabled(true);
                toFile.setEnabled(true);

                viewMessages.setEnabled(true);

                clear.setEnabled(true);
                save.setEnabled(true);

                if (printBytes.isSelected() == true) {
                    MulticastYesBytes.kill();
                } else {
                    MulticastNoBytes.kill();
                }
                Runtime garbage = Runtime.getRuntime();
                garbage.gc();

                break;
            case 7:
                progress.setIndeterminate(false);
                connect.setEnabled(true);
                serviceSelector.setEnabled(true);
                DissconnectDo.setEnabled(false);

                printBytes.setEnabled(true);
                toFile.setEnabled(true);

                viewMessages.setEnabled(true);

                clear.setEnabled(true);
                save.setEnabled(true);

                if (printBytes.isSelected() == true) {

                    try {
                        RequesterYesBytes.kill();
                    } catch (IOException ex) {
                        Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    try {
                        RequesterNoBytes.kill();
                    } catch (IOException ex) {
                        Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                Runtime garb = Runtime.getRuntime();
                garb.gc();
                break;
            default:
                progress.setIndeterminate(false);
                connect.setEnabled(true);
                serviceSelector.setEnabled(true);
                DissconnectDo.setEnabled(false);
                printBytes.setEnabled(true);
                toFile.setEnabled(true);

                viewMessages.setEnabled(true);

                clear.setEnabled(true);
                save.setEnabled(true);

                if (printBytes.isSelected() == true) {
                    ITCHSoupBinTCPYesBytes.kill();
                } else {
                    ITCHSoupBinTCPNoBytes.kill();
                }

                Runtime garbage1 = Runtime.getRuntime();
                garbage1.gc();

                break;
        }

    }//GEN-LAST:event_DissconnectDoActionPerformed

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
        logsArea.setText("");
        switch (serviceSelector.getSelectedIndex()) {

            case 6:
                if (!hostname.getText().isEmpty() && !port.getText().isEmpty()) {

                    progress.setIndeterminate(true);
                    String args[] = new String[4];
                    args[0] = hostname.getText();
                    args[1] = port.getText();
                    args[2] = servicename.getText();
                    args[3] = receiverHost.getText();

                    connect.setEnabled(false);

                    serviceSelector.setEnabled(false);

                    DissconnectDo.setEnabled(true);

                    printBytes.setEnabled(false);

                    toFile.setEnabled(false);
                    viewMessages.setEnabled(false);

                    clear.setEnabled(false);
                    save.setEnabled(false);

                    if (printBytes.isSelected() == true) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    MulticastYesBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    } else {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    MulticastNoBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    }

                } else {
                    JOptionPane.showMessageDialog(this,
                            "IP and Port are requiered!",
                            "Warning",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;

            case 7:
                if (session.getText().isEmpty() || hostname.getText().isEmpty() || port.getText().isEmpty() || seqnum.getText().isEmpty() || seqnumFin.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this,
                            "All fields are requiered!",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);

                } else if (Integer.parseInt(seqnum.getText()) > Integer.parseInt(seqnumFin.getText())) {
                    JOptionPane.showMessageDialog(this,
                            "Final Sequence Number must be  greater than Sequence Number",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else {

                    progress.setIndeterminate(true);
                    String args[] = new String[6];
                    args[0] = hostname.getText();
                    args[1] = port.getText();
                    args[2] = session.getText().trim();
                    args[3] = seqnum.getText();
                    args[4] = seqnumFin.getText();
                    args[5] = servicename.getText();

                    connect.setEnabled(false);

                    serviceSelector.setEnabled(false);
                    DissconnectDo.setEnabled(true);
                    printBytes.setEnabled(false);
                    toFile.setEnabled(false);

                    viewMessages.setEnabled(false);

                    clear.setEnabled(false);
                    save.setEnabled(false);

                    if (printBytes.isSelected() == true) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {

                                try {
                                    RequesterYesBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (Exception ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }

                            }
                        }).start();
                    } else {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {

                                try {
                                    RequesterNoBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (Exception ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }

                            }
                        }).start();
                    }

                }
                break;

            default:
                if (!username.getText().isEmpty() && !password.getText().isEmpty() && !session.getText().isEmpty() && !hostname.getText().isEmpty() && !port.getText().isEmpty() && !seqnum.getText().isEmpty()) {

                    progress.setIndeterminate(true);
                    String args[] = new String[7];
                    args[0] = username.getText();
                    args[1] = password.getText();
                    args[2] = session.getText();
                    args[3] = hostname.getText();
                    args[4] = port.getText();
                    args[5] = seqnum.getText();
                    args[6] = servicename.getText();
                    /*
        try {
            int status = JavaProcess.exec(Unicast.class);
        } catch (IOException ex) {
            Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
        }
                     */

                    connect.setEnabled(false);
                    serviceSelector.setEnabled(false);
                    DissconnectDo.setEnabled(true);
                    printBytes.setEnabled(false);
                    toFile.setEnabled(false);

                    viewMessages.setEnabled(false);

                    clear.setEnabled(false);
                    save.setEnabled(false);

                    if (printBytes.isSelected() == true) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {

                                    ITCHSoupBinTCPYesBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (UnsupportedLookAndFeelException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    } else {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {

                                    ITCHSoupBinTCPNoBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (UnsupportedLookAndFeelException ex) {
                                    Logger.getLogger(ITCHMain.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    }

                } else {
                    JOptionPane.showMessageDialog(this,
                            "All fields are requiered!",
                            "Warning",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
        /*PrintStream con;
        con = new PrintStream(new TextAreaOutputStream(outputTextArea));
        System.setOut(con);
        System.setErr(con);
         */

    }//GEN-LAST:event_connectActionPerformed

    private void servicenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicenameActionPerformed

    private void serviceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSelectorActionPerformed
        // TODO add your handling code here:

        AppProperties appProperties = new AppProperties();
        Properties properties;
        switch (serviceSelector.getSelectedIndex()) {
            case 1:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesNews();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                servicename.setText("NEWS");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);

                break;
            case 2:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesLTP();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                servicename.setText("LTP");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;
            case 3:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesBBO();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                servicename.setText("BBO");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;
            case 4:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesGLIMPSE();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();

                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                servicename.setText("GLIMPSE");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;
            case 5:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesTV();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();

                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                servicename.setText("TV");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;

            case 6:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesTVMulticast();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(false);
                password.setVisible(false);
                session.setVisible(false);
                usernameLabel.setVisible(false);
                passwordLabel.setVisible(false);
                sessionLabel.setVisible(false);
                seqLabel.setVisible(false);
                receiverHost.setVisible(true);
                ipReceiverLabel.setVisible(true);
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                receiverHost.setText(properties.getProperty("receiver"));
                seqnum.setVisible(false);
                servicename.setText("TV Multicast");
                connect.setText("Join Group");
                DissconnectDo.setText("Leave Group");

                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;

            case 7:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesRetransmission();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(false);
                password.setVisible(false);
                session.setVisible(true);
                usernameLabel.setVisible(false);
                passwordLabel.setVisible(false);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                session.setText(properties.getProperty("session"));
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                seqnum.setText(properties.getProperty("sequence"));
                seqnumFin.setText(properties.getProperty("finalSequence"));
                seqnum.setVisible(true);
                seqnumFin.setVisible(true);
                seqLabelFin.setVisible(true);
                servicename.setText("Retransmissions");
                connect.setText("Request");
                DissconnectDo.setText("Stop");
                break;
            case 0:
                containerFields.setVisible(false);
                username.setVisible(true);
                password.setVisible(true);
                session.setVisible(true);
                seqnum.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                sessionLabel.setVisible(true);
                seqLabel.setVisible(true);
                username.setText("");
                password.setText("");
                session.setText(" ");
                hostname.setText("");
                port.setText("");
                seqnum.setText("");
                servicename.setText("");

                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                seqnumFin.setVisible(false);
                seqLabelFin.setVisible(false);
                break;

        }
    }//GEN-LAST:event_serviceSelectorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        // create a jframe
        Main.copyRight.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        Update.setText("");
        logsArea.setText("");
        serviceSelector.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void toFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFileActionPerformed

        if (toFile.isSelected()) {
            userHomeFolder = System.getProperty("user.home") + "\\Desktop";
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Select Folder");
            chooser.setApproveButtonText("Ok");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                userHomeFolder = chooser.getSelectedFile() + "";
            }
            logs.setText("Logs: " + userHomeFolder);
            logs.setVisible(true);
            outputToFiles = true;

        } else {
            logs.setVisible(false);
            outputToFiles = false;
        }
    }//GEN-LAST:event_toFileActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isLetterOrDigit(teclaPulsada)) {
            evt.consume();
        }
        if (username.getText().length() == 6) {
            evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isLetterOrDigit(teclaPulsada)) {
            evt.consume();
        }
        if (password.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_passwordKeyTyped

    private void sessionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sessionKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada) && teclaPulsada != ' ') {
            evt.consume();
        }
        if (session.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_sessionKeyTyped

    private void hostnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostnameKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada) && teclaPulsada != '.') {
            evt.consume();
        }
        if (hostname.getText().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_hostnameKeyTyped

    private void portKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada)) {
            evt.consume();
        }
        if (port.getText().length() == 5) {
            evt.consume();
        }
    }//GEN-LAST:event_portKeyTyped

    private void seqnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seqnumKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada)) {
            evt.consume();
        }
        if (seqnum.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_seqnumKeyTyped

    private void seqnumFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seqnumFinKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada)) {
            evt.consume();
        }
        if (seqnumFin.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_seqnumFinKeyTyped

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        AppProperties appProperties = new AppProperties(username.getText(), password.getText(), session.getText(), hostname.getText(), port.getText(), seqnum.getText());
        switch (serviceSelector.getSelectedItem().toString()) {
            case "NEWS":
                try {
                    appProperties.savePropertiesNews();
                    JOptionPane.showMessageDialog(this,
                            "NEWS Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "LTP":
                try {
                    appProperties.savePropertiesLTP();
                    JOptionPane.showMessageDialog(this,
                            "LTP Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "BBO":
                try {
                    appProperties.savePropertiesBBO();
                    JOptionPane.showMessageDialog(this,
                            "BBO Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "GLIMPSE":
                try {
                    appProperties.savePropertiesGLIMPSE();
                    JOptionPane.showMessageDialog(this,
                            "GLIMPSE Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "TV":
                try {
                    appProperties.savePropertiesTV();
                    JOptionPane.showMessageDialog(this,
                            "TV Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;

            case "TV Multicast":
                try {
                    appProperties = new AppProperties(hostname.getText(), port.getText(), receiverHost.getText());
                    appProperties.savePropertiesTVMulticast();
                    JOptionPane.showMessageDialog(this,
                            "TV Multicast Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "Retransmissions":
                try {
                    appProperties = new AppProperties(session.getText(), hostname.getText(), port.getText(), seqnum.getText(), seqnumFin.getText());
                    appProperties.savePropertiesRetransmission();
                    JOptionPane.showMessageDialog(this,
                            "Retransmission Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }

                break;
            case "OUCH":
                try {
                    appProperties.savePropertiesOUCH();
                    JOptionPane.showMessageDialog(this,
                            "OUCH Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }

                break;
        }
    }//GEN-LAST:event_saveActionPerformed

    private void printBytesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBytesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBytesActionPerformed

    private void receiverHostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiverHostKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada) && teclaPulsada != '.') {
            evt.consume();
        }
        if (receiverHost.getText().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_receiverHostKeyTyped

    private void viewMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMessagesActionPerformed
        // TODO add your handling code here:
        if (viewMessages.isSelected()) {
            logsArea.setEnabled(true);
        } else {
            logsArea.setEnabled(false);
        }
    }//GEN-LAST:event_viewMessagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void exitAll() throws IOException {

        System.out.flush();
        Runtime.getRuntime().halt(0);
    }

    /**
     *
     * @author Juan Jesús Martínez Serrano / juanjmtzs@gmail.com
     *
     *
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DissconnectDo;
    public static javax.swing.JTextArea Update;
    public static javax.swing.JButton clear;
    public static javax.swing.JButton connect;
    private javax.swing.JPanel containerFields;
    private javax.swing.JTextField hostname;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel ipReceiverLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logs;
    public static javax.swing.JTextArea logsArea;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField port;
    private javax.swing.JLabel portLabel;
    public static javax.swing.JCheckBox printBytes;
    public static javax.swing.JProgressBar progress;
    private javax.swing.JTextField receiverHost;
    public static javax.swing.JButton save;
    private javax.swing.JLabel seqLabel;
    private javax.swing.JLabel seqLabelFin;
    private javax.swing.JTextField seqnum;
    private javax.swing.JTextField seqnumFin;
    private javax.swing.JLabel serviceLabel;
    public static javax.swing.JComboBox<String> serviceSelector;
    private javax.swing.JTextField servicename;
    private javax.swing.JTextField session;
    private javax.swing.JLabel sessionLabel;
    public static javax.swing.JCheckBox toFile;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    public static javax.swing.JCheckBox viewMessages;
    // End of variables declaration//GEN-END:variables
}
