/*
 * Copyright (C) 2018 Juan J. Martínez
 * 
 * All rights reserved. This complete software or any portion thereof
 * can be used as reference but may not be reproduced in any manner 
 * whatsoever without the express written permission of the owner.
 * 
 * The purpose of this is to be consulted and used as a referece of 
 * functionallyty.
 * 
 * Developed in Mexico City
 * First version, 2018
 *
 */
/**
 *
 * @author Juan J. Martínez
 * @email juanjmtzs@gmail.com
 * @phone +52-1-55-1247-8044
 * @linkedin https://www.linkedin.com/in/juanjmtzs/
 *
 */
package BMV;

import Handler.MulticastBMVNoBytes;
import Handler.MulticastBMVYesBytes;
import Handler.UnicastBMVNoBytes;
import Handler.UnicastBMVYesBytes;
import Properties.AppProperties;
import Requester.RequesterYesBytes;
import Sphere.Main;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author Juan Jesús Martínez Serrano / juanjmtzs@gmail.com
 */
public class MDBMV extends javax.swing.JFrame {

    RequesterYesBytes req = null;
    public static JFrame windows;
    private boolean outputToFiles = false;
    public static String userHomeFolder = "";

    public static void setUpdate() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Main
     */
    /**
     *
     * @author Juan Jesús Martínez Serrano / juanjmtzs@gmail.com
     *
     *
     */
    public MDBMV() {

        //this.setUndecorated(true);
        initComponents();

        //this.setBackground(new Color(1.0f,1.0f,1.0f,0.5f));
        windows = this;
        ClassLoader classLoader = getClass().getClassLoader();
        ImageIcon img = new ImageIcon(classLoader.getResource("imgs/icon2.png"));

        windows.setIconImage(img.getImage());
        logs.setVisible(false);

        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();
            NimbusLookAndFeel localNimbusLookAndFeel = (NimbusLookAndFeel) UIManager.getLookAndFeel();
            Color derivedColor = localNimbusLookAndFeel.getDerivedColor("nimbusBase", 0.03054375F, -0.3835404F, -0.0980392F, 0, true);
            defaults.put("nimbusOrange", derivedColor);

        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }

        containerFields.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Update = new javax.swing.JTextArea();
        DissconnectDo = new javax.swing.JButton();
        connect = new javax.swing.JButton();
        serviceSelector = new javax.swing.JComboBox<>();
        progress = new javax.swing.JProgressBar();
        containerFields = new javax.swing.JPanel();
        toFile = new javax.swing.JCheckBox();
        logs = new javax.swing.JLabel();
        servicename = new javax.swing.JTextField();
        port = new javax.swing.JTextField();
        hostname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        serviceLabel = new javax.swing.JLabel();
        printBytes = new javax.swing.JCheckBox();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ipReceiverLabel = new javax.swing.JLabel();
        receiverHost = new javax.swing.JTextField();
        group = new javax.swing.JTextField();
        groupLael = new javax.swing.JLabel();
        resendButton = new javax.swing.JButton();
        snapshotButton = new javax.swing.JButton();
        indSnapshotButton = new javax.swing.JButton();
        viewMessages = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        logsArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sphere ITCH");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(1100, 800));

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));

        Update.setEditable(false);
        Update.setBackground(new java.awt.Color(242, 242, 242));
        Update.setColumns(20);
        Update.setForeground(new java.awt.Color(38, 38, 38));
        Update.setRows(5);
        Update.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(Update);

        DissconnectDo.setForeground(new java.awt.Color(38, 38, 38));
        DissconnectDo.setText("Dissconnect");
        DissconnectDo.setEnabled(false);
        DissconnectDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DissconnectDoActionPerformed(evt);
            }
        });

        connect.setForeground(new java.awt.Color(38, 38, 38));
        connect.setText("Connect");
        connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectActionPerformed(evt);
            }
        });

        serviceSelector.setForeground(new java.awt.Color(38, 38, 38));
        serviceSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "BMV Multicast", "BMV Unicast" }));
        serviceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSelectorActionPerformed(evt);
            }
        });

        progress.setBackground(new java.awt.Color(255, 255, 255));
        progress.setOpaque(true);

        containerFields.setBackground(new java.awt.Color(238, 238, 238));

        toFile.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        toFile.setText("Logs in Files");
        toFile.setToolTipText("");
        toFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFileActionPerformed(evt);
            }
        });

        logs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logs.setForeground(new java.awt.Color(51, 51, 51));
        logs.setText("Logs:");

        servicename.setBackground(new java.awt.Color(242, 242, 242));
        servicename.setForeground(new java.awt.Color(38, 38, 38));
        servicename.setText("BMV");
        servicename.setEnabled(false);
        servicename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicenameActionPerformed(evt);
            }
        });

        port.setBackground(new java.awt.Color(242, 242, 242));
        port.setForeground(new java.awt.Color(38, 38, 38));
        port.setToolTipText("33333");
        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });
        port.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                portKeyTyped(evt);
            }
        });

        hostname.setBackground(new java.awt.Color(242, 242, 242));
        hostname.setForeground(new java.awt.Color(38, 38, 38));
        hostname.setToolTipText("200.200.200.200");
        hostname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hostnameKeyTyped(evt);
            }
        });

        password.setBackground(new java.awt.Color(242, 242, 242));
        password.setForeground(new java.awt.Color(38, 38, 38));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        username.setBackground(new java.awt.Color(242, 242, 242));
        username.setForeground(new java.awt.Color(38, 38, 38));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        usernameLabel.setText("Username:");

        passwordLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(51, 51, 51));
        passwordLabel.setText("Password:");

        ipLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ipLabel.setForeground(new java.awt.Color(51, 51, 51));
        ipLabel.setText("IP*:");

        portLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        portLabel.setForeground(new java.awt.Color(51, 51, 51));
        portLabel.setText("Port*:");

        serviceLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        serviceLabel.setForeground(new java.awt.Color(51, 51, 51));
        serviceLabel.setText("Service Name:");

        printBytes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        printBytes.setText("Print Bytes");
        printBytes.setToolTipText("");

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/save.png"))); // NOI18N
        save.setToolTipText("Save Service Configuration");
        save.setPreferredSize(new java.awt.Dimension(31, 31));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/clear.png"))); // NOI18N
        clear.setPreferredSize(new java.awt.Dimension(31, 31));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        ipReceiverLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ipReceiverLabel.setForeground(new java.awt.Color(51, 51, 51));
        ipReceiverLabel.setText("Receiver IP:");

        receiverHost.setBackground(new java.awt.Color(242, 242, 242));
        receiverHost.setForeground(new java.awt.Color(38, 38, 38));
        receiverHost.setToolTipText("200.200.200.200");
        receiverHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receiverHostKeyTyped(evt);
            }
        });

        group.setBackground(new java.awt.Color(242, 242, 242));
        group.setForeground(new java.awt.Color(38, 38, 38));
        group.setToolTipText("1-99");
        group.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                groupKeyTyped(evt);
            }
        });

        groupLael.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        groupLael.setForeground(new java.awt.Color(51, 51, 51));
        groupLael.setText("Group:");

        resendButton.setText("Resend Request");
        resendButton.setEnabled(false);
        resendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resendButtonActionPerformed(evt);
            }
        });

        snapshotButton.setText("Snapshot Request");
        snapshotButton.setEnabled(false);
        snapshotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapshotButtonActionPerformed(evt);
            }
        });

        indSnapshotButton.setText("Index Snapshot Request");
        indSnapshotButton.setEnabled(false);
        indSnapshotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indSnapshotButtonActionPerformed(evt);
            }
        });

        viewMessages.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewMessages.setSelected(true);
        viewMessages.setText("View Messages");
        viewMessages.setToolTipText("");
        viewMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMessagesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerFieldsLayout = new javax.swing.GroupLayout(containerFields);
        containerFields.setLayout(containerFieldsLayout);
        containerFieldsLayout.setHorizontalGroup(
            containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel)
                    .addComponent(ipLabel)
                    .addComponent(portLabel)
                    .addComponent(serviceLabel)
                    .addComponent(ipReceiverLabel)
                    .addComponent(groupLael))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiverHost, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username)
                    .addComponent(password)
                    .addComponent(hostname)
                    .addComponent(port)
                    .addComponent(group)
                    .addComponent(servicename)))
            .addComponent(logs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerFieldsLayout.createSequentialGroup()
                        .addComponent(toFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewMessages, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(printBytes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(resendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snapshotButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indSnapshotButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerFieldsLayout.setVerticalGroup(
            containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipLabel)
                    .addComponent(hostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipReceiverLabel)
                    .addComponent(receiverHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupLael)
                    .addComponent(group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceLabel)
                    .addComponent(servicename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerFieldsLayout.createSequentialGroup()
                        .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toFile)
                            .addComponent(viewMessages))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBytes))
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(snapshotButton)
                    .addComponent(resendButton)
                    .addComponent(indSnapshotButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        logsArea.setBackground(new java.awt.Color(242, 242, 242));
        logsArea.setColumns(20);
        logsArea.setForeground(new java.awt.Color(38, 38, 38));
        logsArea.setRows(5);
        jScrollPane2.setViewportView(logsArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(containerFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(connect, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DissconnectDo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(serviceSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(containerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DissconnectDo)
                    .addComponent(connect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("BMV Feeds", jPanel2);

        jMenu1.setText("About");

        jMenuItem1.setText("Copyright ©");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("by Juan J. Martínez");
        jMenu2.setEnabled(false);
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("BMV Market Data");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DissconnectDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DissconnectDoActionPerformed
        // TODO add your handling code here:

        switch (serviceSelector.getSelectedIndex()) {

            case 1:
                progress.setIndeterminate(false);
                connect.setEnabled(true);
                serviceSelector.setEnabled(true);
                DissconnectDo.setEnabled(false);
                toFile.setEnabled(true);
                viewMessages.setEnabled(true);
                printBytes.setEnabled(true);
                resendButton.setVisible(false);
                snapshotButton.setVisible(false);
                indSnapshotButton.setVisible(false);
                clear.setEnabled(true);
                save.setEnabled(true);

                if (printBytes.isSelected() == true) {
                    MulticastBMVYesBytes.kill();
                } else {
                    MulticastBMVNoBytes.kill();
                }

                Runtime garbage = Runtime.getRuntime();
                garbage.gc();
                break;
            case 2:
                progress.setIndeterminate(false);
                connect.setEnabled(true);
                serviceSelector.setEnabled(true);
                DissconnectDo.setEnabled(false);
                toFile.setEnabled(true);
                viewMessages.setEnabled(true);
                printBytes.setEnabled(true);
                resendButton.setEnabled(false);
                snapshotButton.setEnabled(false);
                indSnapshotButton.setEnabled(false);

                clear.setEnabled(true);
                save.setEnabled(true);

                if (printBytes.isSelected() == true) {
                    UnicastBMVYesBytes.kill();
                } else {
                    UnicastBMVNoBytes.kill();
                }

                Runtime garbage2 = Runtime.getRuntime();
                garbage2.gc();
                break;
        }

    }//GEN-LAST:event_DissconnectDoActionPerformed

    private void connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectActionPerformed
        // TODO add your handling code here:
        logsArea.setText("");
        switch (serviceSelector.getSelectedIndex()) {
            case 1:
                if (!hostname.getText().isEmpty() && !port.getText().isEmpty()) {

                    progress.setIndeterminate(true);
                    String args[] = new String[4];
                    args[0] = hostname.getText();
                    args[1] = port.getText();
                    args[2] = servicename.getText();
                    args[3] = receiverHost.getText();

                    connect.setEnabled(false);
                    serviceSelector.setEnabled(false);
                    DissconnectDo.setEnabled(true);
                    toFile.setEnabled(false);
                    viewMessages.setEnabled(false);
                    printBytes.setEnabled(false);

                    clear.setEnabled(false);
                    save.setEnabled(false);

                    if (printBytes.isSelected() == true) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    MulticastBMVYesBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(MDBMV.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    } else {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    MulticastBMVNoBytes.StartHandling(args);
                                } catch (IOException ex) {
                                    Logger.getLogger(MDBMV.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    }

                } else {
                    JOptionPane.showMessageDialog(this,
                            "IP and Port are requiered!",
                            "Warning",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case 2:
                if (!hostname.getText().isEmpty() && !port.getText().isEmpty() && !username.getText().isEmpty() && !password.getText().isEmpty() && !group.getText().isEmpty()) {

                    progress.setIndeterminate(true);
                    String args[] = new String[7];
                    args[0] = hostname.getText();
                    args[1] = port.getText();
                    args[2] = servicename.getText();
                    args[3] = username.getText();
                    args[4] = password.getText();
                    args[5] = group.getText();
                    args[6] = receiverHost.getText();

                    connect.setEnabled(false);
                    serviceSelector.setEnabled(false);
                    DissconnectDo.setEnabled(true);
                    toFile.setEnabled(false);
                    viewMessages.setEnabled(false);
                    printBytes.setEnabled(false);
                    resendButton.setEnabled(true);
                    snapshotButton.setEnabled(true);
                    indSnapshotButton.setEnabled(true);

                    clear.setEnabled(false);
                    save.setEnabled(false);

                    if (printBytes.isSelected() == true) {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    UnicastBMVYesBytes.StartHandling(args);
                                } catch (Exception ex) {
                                    Logger.getLogger(MDBMV.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    } else {
                        new Thread(new Runnable() {
                            @Override
                            public void run() {
                                try {
                                    UnicastBMVNoBytes.StartHandling(args);
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                    Logger.getLogger(MDBMV.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        }).start();
                    }

                } else {
                    JOptionPane.showMessageDialog(this,
                            "All Fields are requiered!",
                            "Warning",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;

        }
        /*PrintStream con;
        con = new PrintStream(new TextAreaOutputStream(outputTextArea));
        System.setOut(con);
        System.setErr(con);
         */

    }//GEN-LAST:event_connectActionPerformed

    private void serviceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSelectorActionPerformed
        // TODO add your handling code here:

        AppProperties appProperties = new AppProperties();
        Properties properties;
        switch (serviceSelector.getSelectedIndex()) {
            case 1:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesBMVMulticast();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(false);
                password.setVisible(false);
                groupLael.setVisible(false);
                group.setVisible(false);
                usernameLabel.setVisible(false);
                passwordLabel.setVisible(false);
                resendButton.setVisible(false);
                snapshotButton.setVisible(false);
                indSnapshotButton.setVisible(false);
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                receiverHost.setText(properties.getProperty("receiver"));
                receiverHost.setVisible(true);
                ipReceiverLabel.setVisible(true);
                servicename.setText("BMV Multicast");
                connect.setText("Join Group");
                DissconnectDo.setText("Leave Group");

                break;
            case 2:
                containerFields.setVisible(true);
                try {
                    appProperties.loadPropertiesBMVUnicast();
                } catch (Exception e) {
                }
                properties = appProperties.getProperties();
                username.setVisible(true);
                password.setVisible(true);
                groupLael.setVisible(true);
                group.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                resendButton.setVisible(true);
                snapshotButton.setVisible(true);
                indSnapshotButton.setVisible(true);
                hostname.setText(properties.getProperty("ip"));
                port.setText(properties.getProperty("port"));
                username.setText(properties.getProperty("username"));
                password.setText(properties.getProperty("password"));
                group.setText(properties.getProperty("group"));
                receiverHost.setText(properties.getProperty("receiver"));
                receiverHost.setVisible(true);
                ipReceiverLabel.setVisible(true);
                servicename.setText("BMV Unicast");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");

                break;
            case 0:
                containerFields.setVisible(false);
                username.setVisible(true);
                password.setVisible(true);
                usernameLabel.setVisible(true);
                passwordLabel.setVisible(true);
                receiverHost.setVisible(false);
                ipReceiverLabel.setVisible(false);
                groupLael.setVisible(false);
                group.setVisible(false);
                resendButton.setVisible(false);
                snapshotButton.setVisible(false);
                indSnapshotButton.setVisible(false);
                username.setText("");
                password.setText("");
                hostname.setText("");
                port.setText("");
                servicename.setText("");
                receiverHost.setText("");
                group.setText("");
                connect.setText("Connect");
                DissconnectDo.setText("Dissconnect");
                break;

        }
    }//GEN-LAST:event_serviceSelectorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        Main.copyRight.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        Update.setText("");
        logsArea.setText("");
        serviceSelector.setSelectedIndex(0);
    }//GEN-LAST:event_clearActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        AppProperties appProperties;
        switch (serviceSelector.getSelectedItem().toString()) {

            case "BMV Multicast":
                try {
                    appProperties = new AppProperties(hostname.getText(), port.getText(), receiverHost.getText());
                    appProperties.savePropertiesBMVMulticast();
                    JOptionPane.showMessageDialog(this,
                            "BMV Multicast Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "BMV Unicast":
                try {
                    appProperties = new AppProperties(username.getText(), password.getText(), hostname.getText(), port.getText(), group.getText(), true, receiverHost.getText());
                    appProperties.savePropertiesBMVUnicast();
                    JOptionPane.showMessageDialog(this,
                            "BMV Unicast Service Settings Saved",
                            "Saved!",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Something went wrong: " + e,
                            "Error!",
                            JOptionPane.ERROR_MESSAGE);
                }
                break;

        }
    }//GEN-LAST:event_saveActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isLetterOrDigit(teclaPulsada)) {
            evt.consume();
        }
        if (username.getText().length() == 6) {
            evt.consume();
        }
    }//GEN-LAST:event_usernameKeyTyped

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isLetterOrDigit(teclaPulsada)) {
            evt.consume();
        }
        if (password.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_passwordKeyTyped

    private void hostnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hostnameKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada) && teclaPulsada != '.') {
            evt.consume();
        }
        if (hostname.getText().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_hostnameKeyTyped

    private void portKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_portKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada)) {
            evt.consume();
        }
        if (port.getText().length() == 5) {
            evt.consume();
        }
    }//GEN-LAST:event_portKeyTyped

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portActionPerformed

    private void servicenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicenameActionPerformed

    private void toFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFileActionPerformed
        // TODO add your handling code here:

        if (toFile.isSelected()) {

            userHomeFolder = System.getProperty("user.home") + "\\Desktop";
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Select Folder");
            chooser.setApproveButtonText("Ok");
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                userHomeFolder = chooser.getSelectedFile() + "";
            }
            logs.setText("Logs: " + userHomeFolder);
            logs.setVisible(true);
            outputToFiles = true;

        } else {

            logs.setVisible(false);
            outputToFiles = false;
        }
    }//GEN-LAST:event_toFileActionPerformed

    private void receiverHostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receiverHostKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada) && teclaPulsada != '.') {
            evt.consume();
        }
        if (receiverHost.getText().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_receiverHostKeyTyped

    private void groupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_groupKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (!Character.isDigit(teclaPulsada)) {
            evt.consume();
        }
        if (group.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_groupKeyTyped

    private void resendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendButtonActionPerformed
        // TODO add your handling code here:
        ResendRequest resendRequest = new ResendRequest();
        resendRequest.groupTextField.setText(group.getText());
        resendRequest.setVisible(true);

    }//GEN-LAST:event_resendButtonActionPerformed

    private void snapshotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapshotButtonActionPerformed
        // TODO add your handling code here:
        SnapshotRequest snapshotRequest = new SnapshotRequest();
        snapshotRequest.groupTextField.setText(group.getText());
        snapshotRequest.setVisible(true);
    }//GEN-LAST:event_snapshotButtonActionPerformed

    private void indSnapshotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indSnapshotButtonActionPerformed
        // TODO add your handling code here:

        IndexSnapshotRequest IndexSnapshotRequest = new IndexSnapshotRequest();
        IndexSnapshotRequest.groupTextField.setText(group.getText());
        IndexSnapshotRequest.setVisible(true);
    }//GEN-LAST:event_indSnapshotButtonActionPerformed

    private void viewMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMessagesActionPerformed
        // TODO add your handling code here:
        if (viewMessages.isSelected()) {
            logsArea.setEnabled(true);
        } else {
            logsArea.setEnabled(false);
        }
    }//GEN-LAST:event_viewMessagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public void exitAll() throws IOException {

        System.out.flush();
        Runtime.getRuntime().halt(0);
    }

    /**
     *
     * @author Juan Jesús Martínez Serrano / juanjmtzs@gmail.com
     *
     *
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton DissconnectDo;
    public static javax.swing.JTextArea Update;
    public static javax.swing.JButton clear;
    public static javax.swing.JButton connect;
    private javax.swing.JPanel containerFields;
    private javax.swing.JTextField group;
    private javax.swing.JLabel groupLael;
    private javax.swing.JTextField hostname;
    public static javax.swing.JButton indSnapshotButton;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JLabel ipReceiverLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logs;
    public static javax.swing.JTextArea logsArea;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField port;
    private javax.swing.JLabel portLabel;
    public static javax.swing.JCheckBox printBytes;
    public static javax.swing.JProgressBar progress;
    private javax.swing.JTextField receiverHost;
    public static javax.swing.JButton resendButton;
    public static javax.swing.JButton save;
    private javax.swing.JLabel serviceLabel;
    public static javax.swing.JComboBox<String> serviceSelector;
    private javax.swing.JTextField servicename;
    public static javax.swing.JButton snapshotButton;
    public static javax.swing.JCheckBox toFile;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    public static javax.swing.JCheckBox viewMessages;
    // End of variables declaration//GEN-END:variables
}
