/*
 * Copyright (C) 2018 Juan J. Martínez
 * 
 * All rights reserved. This complete software or any portion thereof
 * can be used as reference but may not be reproduced in any manner 
 * whatsoever without the express written permission of the owner.
 * 
 * The purpose of this is to be consulted and used as a referece of 
 * functionallyty.
 * 
 * Developed in Mexico City
 * First version, 2018
 *
 */

/**
 *
 * @author Juan J. Martínez
 * @email juanjmtzs@gmail.com
 * @phone +52-1-55-1247-8044
 * @linkedin https://www.linkedin.com/in/juanjmtzs/
 *
 */

package Sphere;

import Properties.AppProperties;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ncoder.CryptoNCoder;

public class License extends javax.swing.JFrame {

    /**
     * Creates new form NewOrder
     */
    private String accType;
    private String timeInForce;
    private JFrame windows;
    public static String mDPrice = "";

    public License() {
        initComponents();
        //this.setUndecorated(true);
        //this.setBackground(new Color(1.0f,1.0f,1.0f,0.5f));
        windows = this;
        ClassLoader classLoader = getClass().getClassLoader();
        ImageIcon img = new ImageIcon(classLoader.getResource("imgs/icon2.png"));

        windows.setIconImage(img.getImage());
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        licenseTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("License");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("License:");

        licenseTextField.setBackground(new java.awt.Color(242, 242, 242));
        licenseTextField.setForeground(new java.awt.Color(38, 38, 38));
        licenseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseTextFieldActionPerformed(evt);
            }
        });
        licenseTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                licenseTextFieldKeyTyped(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(38, 38, 38));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(licenseTextField)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(licenseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        AppProperties appProperties;
        try {
            appProperties = new AppProperties(licenseTextField.getText());
            appProperties.savePropertiesLicense();

        } catch (Exception e) {

        }
        try {
            CryptoNCoder cryptoNCoder = new CryptoNCoder();
            String dateStri = cryptoNCoder.decrypt(Main.Key, licenseTextField.getText()).substring(5, 18);
            Date expiry = new Date(Long.parseLong(dateStri));
            Date date = new Date();
            SimpleDateFormat df = new SimpleDateFormat("MMM dd yyyy");

            if (date.compareTo(expiry) > 0) {
                JOptionPane.showMessageDialog(this,
                        "Your License has expired, please contact us: contact@hiketech.com.mx",
                        "License Expired",
                        JOptionPane.ERROR_MESSAGE);
                Main.licenseText = "License Type: " + cryptoNCoder.decrypt(Main.Key, licenseTextField.getText()).substring(0, 4)
                        + "<br>"
                        + "License State: Expired"
                        + "<br>"
                        + "Expiry Date: " + df.format(expiry);
            } else if (date.compareTo(expiry) < 0) {
                this.dispose();
                JOptionPane.showMessageDialog(this,
                        "Take full Advantage of Sphere, it expires " + df.format(expiry),
                        "Correct License",
                        JOptionPane.INFORMATION_MESSAGE);
                Main.licenseText = "License Type: " + cryptoNCoder.decrypt(Main.Key, licenseTextField.getText()).substring(0, 4)
                        + "<br>"
                        + "License State: Active"
                        + "<br>"
                        + "Expiry Date: " + df.format(expiry);

            } else if (date.compareTo(expiry) == 0) {
                JOptionPane.showMessageDialog(this,
                        "Your License expires today, please contact us: contact@hiketech.com.mx",
                        "License About to Expire",
                        JOptionPane.WARNING_MESSAGE);
                Main.licenseText = "License Type: " + cryptoNCoder.decrypt(Main.Key, licenseTextField.getText()).substring(0, 4)
                        + "<br>"
                        + "License State: Active"
                        + "<br>"
                        + "Expiry Date: " + df.format(expiry);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this,
                        "Your License is not valid, please contact us: contact@hiketech.com.mx",
                        "Invalid License",
                        JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Your License is not valid, please contact us: contact@hiketech.com.mx",
                    "Invalid License",
                    JOptionPane.ERROR_MESSAGE);
        }
        Main.updateCopy();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void licenseTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licenseTextFieldKeyTyped
        // TODO add your handling code here:
        char teclaPulsada = evt.getKeyChar();
        if (licenseTextField.getText().length() == 18) {
            evt.consume();
        }
    }//GEN-LAST:event_licenseTextFieldKeyTyped

    private void licenseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField licenseTextField;
    // End of variables declaration//GEN-END:variables
}
